### ISSUE TITLE
Failed to rename file.

### ISSUE THREAD

**Issue by LGeorgii** [wojciech-kulik/xcodebuild.nvim#84]
Hello! 
Failed to rename file in the project.
Logs from xcodebuild_nvimtree:

```
/Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:156:in `block (2 levels) in get_targets_for_file': undefined method `real_path' for nil (NoMethodError)
```

      result << target.name if file.real_path.to_s == file_path
                                   ^^^^^^^^^^
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:155:in `each'
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:155:in `block in get_targets_for_file'
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:154:in `each'
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:154:in `get_targets_for_file'
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:91:in `move_file'
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:180:in `handle_action'
	from /Users/georgiilysenko/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:219:in `<main>'
	
	
I'm sorry if i've made a dumb mistake, i'm new to Neovim and trying to setup environment for the first time)

**Comment by wojciech-kulik** [comment]
Hmm, this is weird, the code iterates through file references, so it should return nil `file`:

```
  project.targets.each do |target|
    target.source_build_phase.files_references.each do |file|
      result << target.name if file.real_path.to_s == file_path
    end
```

Maybe something is broken with your project file? Some missing reference?

Also, please make sure that your Ruby and CocoaPods/Xcodeproj are up to date

**Comment by wojciech-kulik** [comment]
@LGeorgii I pushed some minor changes, but possibly it could be the root cause of this issue. Please update the plugin and let me know if it helped.

**Comment by LGeorgii** [comment]
@wojciech-kulik thanks for a quick feedback! Issue still exist on my side, but i believe it can be caused by my config(i'm very new to Neovim and now struggles in every direction in it 🫠) or my xcode project. I'll try to fix it on my side and let you know if succeeded.

**Comment by wojciech-kulik** [comment]
Alternatively, you can save this simple code as `test.rb`:

```ruby
require "xcodeproj"

project = Xcodeproj::Project.open("PATH_TO_XCODEPROJ")

project.native_targets.each do |target|
  target.source_build_phase.files_references.each do |file|
    if file.nil?
      puts "Found nil file in native target: #{target.name}"
    end
  end
end

project.targets.each do |target|
  target.source_build_phase.files_references.each do |file|
    if file.nil?
      puts "Found nil file in target: #{target.name}"
    end
  end
end
```

Then run:
```
ruby test.rb
```

It should at least print out the target name that is causing the problem. Maybe it will help you to track the issue.

**Comment by LGeorgii** [comment]
@wojciech-kulik Thank you a lot for script. I've managed to fixed the issue. I'll write down the root cause of this, may it'll be helpful for someone else
When i tried to create first file in my project using vim, empty "BuildFile" was created. 
<img width="634" alt="Screenshot 2024-03-10 at 13 53 35" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/116944025/7e5f2a8d-2c19-417e-8c82-1656c7000c0c">
I thought this is necessary file for project to create new files from vim, so i left it. This file caused errors during renaming. After i deleted it - issue was fixed.

**Comment by wojciech-kulik** [comment]
Great 🎊 how did you create this faulty file? Do you have any steps to cause this behavior?

**Comment by LGeorgii** [comment]
To be honest i don't remember exact steps. I just remember that i tried to create a new file for the first time and this file had been also created alongside with the file i wanted.

**Comment by wojciech-kulik** [comment]
Ok, I’m closing the issue, if you encounter the problem again, feel free to reopen it :)
